### ISSUE TITLE
include-file-0.1.0.2 can't compile its Setup.hs file

### ISSUE THREAD

**Issue by peti** [Daniel-Diaz/include-file#1]
Citing from http://hydra.cryp.to/build/1226876/log/raw:

```
Setup.hs:3:8:
    Could not find module ‘System.Random’
    Use -v to see a list of the files searched for.
```

Setup.hs depends on the `random` library, but the library itself does not. Thus, a clean build environment cannot compile Setup.hs.

**Comment by Daniel-Diaz** [comment]
I will work on a fix soon. Thanks for the report.

**Comment by Daniel-Diaz** [comment]
I think this was fixed long ago. Re-open if this is not the case.
